Increase code quality to 9000%
VedalAI/neuro-amongus pull request #34
Opened 2023-04-07 13:16 UTC by Alexejhero

- Make `PathfindingHandler` a singleton and move arrow logic
- Create unstable collections, each element has a UnityEngine.Object anchor, if that is destroyed then the element is automatically removed from the collection
- Split `VisionHandler` into `PlayerControlVisionHandler` and `DeadBodyVisionHandler`

2023-04-09 23:20 UTC, alekso56 commented
When socket is not connected on startup, the player is forced to walk down forever.

2023-04-10 00:16 UTC, Alexejhero commented
> When socket is not connected on startup, the player is forced to walk down forever.

That was on purpose to test the movement handler, but it's been removed since.

The python side has not been updated to integrate with the new socket serialization system anyway.

2023-04-10 04:31 UTC, alekso56 commented
Im curious, if you are going to send partial strings anyways, why not make a data class and then send that as json then decode as json on python side?

2023-04-10 07:12 UTC, Alexejhero commented
> Im curious, if you are going to send partial strings anyways, why not make a data class and then send that as json then decode as json on python side?

JSON has a lot of fluff (for example the name of the keys is repeated in every object) so it's very inefficient for socket purposes. Additionally, since we want to be saving this data to a file, we want the file to be as small as possible.

2023-04-10 14:08 UTC, alekso56 commented
maybe can do something like this on python side, com protocol is currently sending zero data from the client, so might want to fix that first.
```

from dataclasses import dataclass

from numpy import byte

from bytechomp import Reader


@dataclass
class PositionData:
    TotalDistance: float
    NextNodePositionX: float
    NextNodePositionY: float


@dataclass
class DeadBodyData:
    ParentId: byte
    LastSeenPositionX: float
    LastSeenPositionY: float
    FirstSeenTime: float
    NearbyPlayersCount: byte
    NearbyPlayers: list[byte]


@dataclass
class DoorData:
    position: PositionData
    IsOpen: bool


@dataclass
class VentData:
    position: PositionData
    ConnectingVentsCount: byte
    ConnectingVents: list[PositionData]


@dataclass
class OtherPlayerData:
    id: byte
    LastSeenPositionX: float
    LastSeenPositionY: float
    LastSeenTime: float
    TimesSawVent: byte
    RoundTimeVisible: float
    GameTimeVisible: float


@dataclass
class Frame:
    seenBodiesCount: byte
    seenBodies: list[DeadBodyData]
    DidKill: bool
    SabotageUsed: byte
    DoorsUsed: byte
    DidReport: bool
    DidVent: bool
    NearbyDoorsCount: byte
    NearbyDoors: list[DoorData]
    NearbyVentsCount: byte
    NearbyVents: list[VentData]
    LastSeenCount: byte
    LastSeen: list[OtherPlayerData]


def read(stream):
    print("Creating frame from byte array")
    reader = Reader[Frame]().allocate()
    if reader << stream.read(512):
        # construct dataclass
        my_struct = reader.build()
        reader.clear()
        return my_struct
```

2023-04-10 14:24 UTC, Vedal987 requested changes
do better serialization

2023-04-10 20:10 UTC, Alexejhero commented
This PR will be ready for a re-riew once I've added deserialization on the python side

2023-04-13 18:12 UTC, JohnyDaison commented on Neuro/Recording/Frame.proto
> +    optional HeaderFrame Header = 5;
Why did you put it on this line and not the end the block?

2023-04-17 20:50 UTC, Vedal987 commented
idk probably fine

2023-04-17 20:50 UTC, Vedal987 approved these changes

2023-04-17 20:50 UTC, merged