Minigame solvers
VedalAI/neuro-amongus pull request #38
Opened 2023-04-08 11:58 UTC by Linkis20

Doing tasks in Airship Map.
Currently implemented:
- Stage 2 of Upload Data in Armory
- Door Sabotage Airship

2023-04-08 12:03 UTC, Linkis20 commented
[EBro912](https://github.com/EBro912) commits are in here, but that is because I stated with https://github.com/VedalAI/neuro-amongus/pull/33 branch.

2023-04-08 12:41 UTC, Linkis20 commented
Made https://github.com/Linkis20/neuro-amongus/tree/minigame-solvers-clean if you need one without [EBro912](https://github.com/EBro912) commits.

2023-04-21 20:33 UTC, Alexejhero requested changes
Requesting changes for all 3 solvers, if you do not want to change some of them feel free to remove them from the PR and someone else will take them

2023-04-21 20:33 UTC, Alexejhero commented on Neuro/Minigames/Solvers/DoorSabotageAirshipSolver.cs
The cursor isn't visible from the start of the movement, you call InsertCard before showing the cursor

2023-04-21 20:33 UTC, Alexejhero commented on Neuro/Minigames/Solvers/UploadDataAirshipSolver.cs
Neuro isn't psychic, she shouldn't know where the hotspot is like that.

Implement some sort of scanning motion that scans the whole screen area until it gets to Poor, and then starts scanning a smaller area until it gets to Good, and so on until it goes to Perfect.

2023-04-21 20:33 UTC, Alexejhero commented on Neuro/Minigames/Solvers/TuneRadioSabotageSolver.cs
This solver looks a bit janky, the dial is turned in the correct direction always, the movement is very slow and once it reaches the target, it jitters back and forth.

2023-04-22 20:02 UTC, Alexejhero commented
Someone else is working on a solver for the Upload Data Airship task

2023-04-29 14:32 UTC, Alexejhero approved these changes

2023-04-29 14:32 UTC, merged